config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :videos
  resources :tags
  devise_for :users
  get 'welcome/index'

  get '/import', to: 'import#index'
  post '/import/set', to: 'import#set'
  get '/export', to: 'import#export'
  

  root 'welcome#index'

  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)

    # binding.pry

    if user.is_admin?
        can :manage, :all
    else
        can :manage, Video, :user_id => user.id
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  Precompile.ignore { rolify }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  resourcify
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :videos
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :user
  resourcify

  acts_as_taggable

  validates :video_hash, presence: true
  validates :video_hash, uniqueness: { scope: :user, message: "User already has this video"}

  paginates_per 12
  max_paginates_per 50

  def paused_at 
    read_attribute(:paused_at) || 0
  end

  def duration
    read_attribute(:duration) || 0
  end

  # small: 120x90
  # large: 480x360
  def thumbnail_url
  	read_attribute(:thumbnail_url) || 'http://placehold.it/480x360'
  end

  def update_remote_metadata
  	PotatrWorker.perform_async(self.video_hash,1)
  end

  def progress
    if self.paused_at == 0 || self.paused_at == nil 
      return 0
    end
    self.paused_at / self.duration.to_f * 100
  end

  # super ugly. the default delimiter for acts-as-taggable-on is a comma, but it server it up as 
  # an array
  def tag_list
    concat = ""
    super.each { | tag |  concat.length == 0 ? concat = tag : concat = concat + ", #{tag}" }
    concat
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # whut
  protect_from_forgery 
  before_action :authenticate_user!
  check_authorization :unless => :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    puts "Access denied"
    respond_to do |format|
      format.json { render nothing: true, status: :forbidden }
      format.html { redirect_after_login_or_main_root }
    end
  end


  private

  def redirect_after_login_or_main_root
    store_location_for :user, request.path
    redirect_to user_signed_in? ? main_app.root_url : new_user_session_path, alert: exception.message
  end
end

app/controllers/import_controller.rb
class ImportController < ApplicationController
  load_and_authorize_resource :video, :through => :current_user

	def set
		@results = []

		list = params[:video_list].split(/\r\n/)
		# binding.pry
		list.each do |video|
			video_split_up = video.split(":")
			v = Video.new
			v.user = current_user
			v.video_hash = video_split_up[0]
			v.tag_list = video_split_up[1] if video_split_up.length > 1 
			v.paused_at = video_split_up[2] if video_split_up.length > 2
			begin
				v.save!
				@results.push "Saved #{v.video_hash}"
			rescue => e
				@results.push "Failed to add #{v.video_hash}: #{e}"
			end
		end
	end

	def index
	end

	def export
		@videos = Video.accessible_by(current_ability)
	end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def index
		popular_tags = ActsAsTaggableOn::Tag.most_used
		user_tags = Video.where(user_id: 1).tag_counts_on(:tags)
		@tags = {popular_tags: popular_tags, user_tags: user_tags}
	end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  #skip_before_action :verify_authenticity_token, if: :json_request?
  skip_before_action :verify_authenticity_token
  load_and_authorize_resource :through => :current_user
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  after_action :allow_iframe, only: [:new, :show]


  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.where(user: current_user).order(updated_at: :desc)
    if (params[:tag].present?) 
      @videos = @videos.tagged_with(params[:tag])
    end
    @user_tags = Video.where(user: @current_user).tag_counts_on(:tags).order('name')
    @videos = @videos.page params[:page]
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)
    @video.user = current_user
    respond_to do |format|
      if @video.save
        @video.update_remote_metadata
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def json_request?
      request.format.json?
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:name, :video_hash, :paused_at, :tag_list)
    end


    def allow_iframe
      response.headers.except! 'X-Frame-Options'
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_authorization_check
  skip_before_action :authenticate_user!, :only => [:index]
  def index
  #	redirect_to :videos

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# https://gist.github.com/suryart/7418454
	def bootstrap_class_for flash_type
		{ success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
	end

	def flash_messages(opts = {})
		flash.each do |msg_type, message|
			concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
				concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
				concat message 
			end)
		end
		nil
	end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/import/export.erb
Here you go:

<div class="container">
	<% @videos.each do |v| %>  
	<div class="row">
		<div class="col-xs-4 portfolio-item">
			<%= v.video_hash %>:<%= v.tag_list %>:<%= v.paused_at %>
		</div>  
	</div>
	<% end %>
</div>

app/views/import/index.erb
<%= form_tag(import_set_path, method: "post") do %>
<%= text_area_tag(:video_list, "", size: "24x6") %>
<br>
<%= submit_tag("Import") %>
<% end %>

app/views/import/set.erb
Alrighty, thanks.

<div class="container">
	<% @results.each do |result| %>  
	<div class="row">
		<div class="col-xs-4 portfolio-item">
			<%= result %>
		</div>  
	</div>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Potatr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  
</head>
<body>


  <div class="navbar navbar-default navbar-inverse">
   <div class="container-fluid">
    <div class="navbar-header">
     <a href="/" class="navbar-brand">potatr</a>
   </div>
   <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <% if user_signed_in? %>

    <ul class="nav navbar-nav">
      <li>
          <%= link_to new_video_path, title: "Add new video" do %>
              <span class="glyphicon glyphicon-plus" aria-hidden="true">
          <% end %>
      </li>
      <li>
        <%= link_to  tags_path, title: "Tags" do %>
            <span class="glyphicon glyphicon-tags" aria-hidden="true">
        <% end %>
       </li>
    </ul>
    <% end %>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
     <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">  <span class="glyphicon glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
</a>
          <ul class="dropdown-menu">
            <li><a href="/export">Export</a></li>
            <li><a href="/import">Import</a></li>
            <li><a href="#">Settings</a></li>
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        </li>
          </ul>

        </li>
        <%else%>
        <li>
  <%= link_to('Login', new_user_session_path)  %>  
        </li>
        <% end %>
    </ul>

  </div>
</div>
</div>


<%= flash_messages %>

<div class="container-fluid bodyContent">
	<%= yield %>
</div>


<div class="container">

  <hr>

  <!-- Footer -->
  <footer>
    <div class="row">
      <div class="col-lg-12">
      <a href="javascript:(function(){if(window.myBookmarklet!==undefined){myBookmarklet();}else{document.body.appendChild(document.createElement('script')).src='https://potatr.duckdns.org/bookmarklet.js?';}})();">Bookmarklet</a>
      <p>Copyright &copy; Big N Tall 2032</p>
      </div>
    </div>
  </footer>

</div>
<!-- /.container -->

</body>
</html>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing popular tags</h1>

<table>
  <thead>
    <tr>
      <th>tag name</th>
      <th>count</th>
    </tr>
  </thead>

  <tbody>
    <% @tags[:popular_tags].each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= tag.taggings_count %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<h1>Listing your tags</h1>

<table>
  <thead>
    <tr>
      <th>tag name</th>
      <th>count</th>
    </tr>
  </thead>

  <tbody>
    <% @tags[:user_tags].each do |tag| %>
      <tr>
        <td><%= link_to tag.name, :controller => "videos", :tag => tag.name %></td>
        <td><%= tag.taggings_count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
  <%= link_to('Back to Welcome', welcome_index_path)  %>  

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= @video.title %>

<% unless @video.persisted? %>
  <div class="field">
    <%= f.label :video_hash%><br>
    <%= f.text_field :video_hash, :value => params[:v] %>
  </div> 
<% end %>
  <div class="field">
    <%= f.label :tag_list %><br>
    <%= f.text_field :tag_list, 'data-role'=>'tagsinput' %>
  </div>
<!--   <div class="field">
    <%= f.label :paused_at %><br>
    <%= f.number_field :paused_at %>
  </div> -->
<!--   <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<div class="page-header">
  <% if params[:tag] %>
  <h3>For "<%= params[:tag] %>"</h3>
  <% else %>
  <h3>All Videos</h3>
  <% end %>
</div>

 <STYLE type="text/css">
.css1 { font-size: 1.0em; }
.css2 { font-size: 1.4em; }
.css3 { font-size: 1.6em; }
.css4 { font-size: 1.8em; }
</STYLE>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-10">
    <div class="row"> <!-- thumbs -->
    <div class="col-md-10" >
        <%= paginate @videos %>
        <% @videos.each_slice(3) do |videos| %>
        <div class="row">
          <% videos.each do |video| %>   
          <div class="col-xs-4 col-md-4 portfolio-item">
            <%= link_to video do %>
              <img class="img-responsive" src="<%= video.thumbnail_url %>">
            <% end %>
            <div class="caption pull-center separated">
              <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: <%= video.progress %>%; ">
                    <%= video.paused_at != 0 ? "#{ChronicDuration.output(video.paused_at, :format => :long) }": "Unwatched" %>
                </div>
              </div>

              <%= link_to video.title, video, class: "pull-center separated" %>
              (<%= ChronicDuration.output(video.duration, :format => :chrono) %>)
            </div>
           </div>
           <% end %>
         </div>
        <% end %>
      </div>
  </div>
    </ul>
    </div>
    <div class="col-md-2"> <!-- tags -->
      <%= render "tags" %>
    </div>

  </div>
</div>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p>
  <strong>tag list:</strong>
  <%= @video.tag_list %>
</p>


<p>
  <strong>Name:</strong>
  <%= @video.name %>
</p>

<p>
  <strong>Hash:</strong>
  <%= @video.video_hash %>
</p>

<p>
  <strong>Paused at:</strong>
  <%= ChronicDuration.output(@video.paused_at, :format => :long) %>
</p>

<p>
  <strong>Title:</strong>
  <%= @video.title %>
</p>

<div id="content">
	<div id="player"></div>
</div>


<script type="text/javascript" src="/lib/jquery-1.11.2.js"></script>
<script type="text/javascript" src="/lib/jquery-ui-1.11.4/jquery-ui.js"></script>
<script type="text/javascript" src="/js/app.js"></script>
<script type="text/javascript">

	function createPlayer() {
		if (typeof YT === 'undefined' || typeof YT.Player === 'undefined') {
			setTimeout(createPlayer, 100);
		} else {
			createYTPlayerForVideo("<%= @video.video_hash %>",  <%= @video.paused_at %>, <%= @video.id %>);
		}
	}

	$( document ).ready( function() {
		createPlayer();	
	});
</script>

<div class="container">
<%= link_to 'New', new_video_path,  class: "btn btn-success pull-center" %>
<%= link_to 'Edit', edit_video_path(@video),  class: "btn btn-success pull-center" %>
<%= link_to 'Back', videos_path,  class: "btn btn-success pull-center" %>
<%= link_to 'Destroy', @video, class: "btn btn-success", method: :delete, data: { confirm: 'Are you sure?' } %> 


</div>

app/views/welcome/index.html.erb
Potatr is a simple bookmarking service for Youtube. With Tags.